### PR TITLE
Add the packaging metadata to build the shadow snap

### PR DESCRIPTION
**Pull request by come-maiz**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

Uploading the snap to the ubuntu store will give you transactional automatic updates. This snap seems to me good enough to publish in the edge channel, which will make it really easy to do crowd-testing before the stable release.

To give it a try:

$ sudo apt install git snapcraft
$ git clone https://github.com/elopio/shadow
$ cd shadow
$ git checkout snapcraft
$ snapcraft
$ sudo snap install *.snap --dangerous
$ shadow

If you have any doubts or comments, please let me know :)

**Comment by rynomster** [comment]
Thanks for the PR, I'm currently away from home visiting family, so I don't have linux right now. I'll be able to test it on Tuesday evening

**Comment by rynomster** [comment]
Thanks again @elopio! it certainly makes some things easier :) I'm assuming you can commit the snapcraft file to a global repo, and automagically clone the repos and allow people to build that way? still reading more about it.

**Comment by elopio** [comment]
Thanks to you @rynomster!
I'm not sure I understand your question. We have a store where you upload new revisions, and the users get automatic updates. They just have to run snap install shadow, they don't have to build it. As a next step, I recommend you to register the snap name at https://myapps.developer.ubuntu.com/dev/click-apps/register-name/ and upload a snap to the edge channel.

The we can hook your travis to make releases to edge on each change to master, and to candidate every time there is a tag.

**Comment by elopio** [comment]
Hey @rynomster, I was wondering if you had time to take a look at the store.
If you have some time, we can jump into a chat or hangout to talk about pushing new versions to the edge channel for every change on your master, so you get happy early adopters :)

**Comment by rynomster** [comment]
Sure, can we setup a time? When will be convenient for you? What time zone
are you in?

On Nov 29, 2016 08:05, "Leo Arias" <notifications@github.com> wrote:

Hey @rynomster <https://github.com/rynomster>, I was wondering if you had
time to take a look at the store.
If you have some time, we can jump into a chat or hangout to talk about
pushing new versions to the edge channel for every change on your master,
so you get happy early adopters :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/shadowproject/shadow/pull/61#issuecomment-263484710>,
or mute the thread

**Comment by elopio** [comment]
@rynomster I'm in Costa Rica, that's UTC -6, so for me any time after 14:00 UTC is good.
However, in my team there are good people from all the time zones you can imagine. Feel free to pick any day and time.

**Comment by come-maiz** [comment]
Ping @rynomster.
(sorry to ping here, but I don't have your email :)
I'm just coming back from holidays, and catching up on my pending conversations from last year. I'll be available now to work with you enabling the continuous delivery. Please let me know when you have some time.

Happy new year!

**Comment by rynomster** [comment]
Sorry I never got back to you, I just realised. How's tomorrow? Around
14:30 utc? You can email me on sdcdev@shadow.cash, then we can get into a
chat.. We also have a slack, but Skype or whatever works

**Comment by come-maiz** [comment]
@rynomster 14:30 is great. I will send you an invite to our usual hangout, that is what I've found to work best with my sad latinamerican bandwidth. But we can try skype if you prefer that, just let me know.

**Comment by rynomster** [comment]
Awesome hangouts are fine :)

**Pull request merged**
